import matplotlib.pyplot as plt
import numpy as np
import tkinter

print("""
1.Wykres y(x)
2.Jeden wykres y1(x1),y2(x2) 
3.Dwa wykresy y1(x1),y2(x2)
""")
choose = input()
if int(choose) == 1:
    x1 = np.loadtxt("text", usecols=[0])
    y1 = np.loadtxt("text", usecols=[1])
    plt.plot(x1, y1, "o")
    title = input("title: ")
    plt.title(title)
    xx = input("label x:")
    yy = input("label y:")
    plt.xlabel(r"" + xx)
    plt.ylabel(r"" + yy)
    z = np.polyfit(x1, y1, 1)
    p = np.poly1d(z)
    plt.plot(x1, p(x1), "r-")
    plt.text(2, 100, "y=%.6fx+%.6f" % (z[0], z[1]), ha='center')
    plt.grid(True)
elif int(choose) == 2:
    x1 = np.loadtxt("text", usecols=[0])
    y1 = np.loadtxt("text", usecols=[1])
    x2 = np.loadtxt("text", usecols=[2])
    y2 = np.loadtxt("text", usecols=[3])
    plt.plot(x1, y1, "o")
    z = np.polyfit(x1, y1, 1)
    p = np.poly1d(z)
    plt.plot(x1, p(x1), "r-")
    plt.text(2, 100, "y=%.6fx+%.6f" % (z[0], z[1]), ha='center')
    plt.grid(True)

    plt.plot(x2, y2, "o")
    title = input("title: ")
    plt.title(title)
    labx = input("label x:")
    laby = input("label y:")
    plt.xlabel(r"" + labx)
    plt.ylabel(r"" + laby)
    z = np.polyfit(x2, y2, 1)
    p = np.poly1d(z)
    plt.plot(x2, p(x2), "r-")
    plt.text(2, 1000, "y=%.6fx+%.6f" % (z[0], z[1]), ha='center')
    plt.grid(True)
elif int(choose) == 3:
    x1 = np.loadtxt("text", usecols=[0])
    y1 = np.loadtxt("text", usecols=[1])
    x2 = np.loadtxt("text", usecols=[2])
    y2 = np.loadtxt("text", usecols=[3])
    plt.subplot(2, 1, 1)
    plt.plot(x1, y1, '.-')
    title = input("title: ")
    plt.title(title)
    labx1 = input("label x:")
    laby1 = input("label y:")
    plt.xlabel(r"" + labx1)
    plt.ylabel(r"" + laby1)
    z = np.polyfit(x1, y1, 1)
    p = np.poly1d(z)
    plt.plot(x1, p(x1), "r-")
    plt.text(1, 1, "y=%.6fx+%.6f" % (z[0], z[1]), ha='center')
    plt.grid(True)

    plt.subplot(2, 1, 2)
    plt.plot(x2, y2, '.-')
    labx2 = input("label x:")
    laby2 = input("label y:")
    plt.xlabel(r"" + labx2)
    plt.ylabel(r"" + laby2)
    z = np.polyfit(x2, y2, 1)
    p = np.poly1d(z)
    plt.plot(x2, p(x2), "r-")
    plt.text(1, 1, "y=%.6fx+%.6f" % (z[0], z[1]), ha='center')
    plt.grid(True)

plt.show()